// File generated by hgctl. Modify as required.
// See: https://higress.io/zh-cn/docs/user/wasm-go#2-%E7%BC%96%E5%86%99-maingo-%E6%96%87%E4%BB%B6

package main

import (
	"fmt"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-proxy/config"
	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-proxy/provider"
	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-proxy/util"
	"github.com/alibaba/higress/plugins/wasm-go/pkg/streamxform"
	"github.com/alibaba/higress/plugins/wasm-go/pkg/streamxform/guard"

	"github.com/higress-group/wasm-go/pkg/log"
	"github.com/higress-group/wasm-go/pkg/wrapper"

	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm"
	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

const (
	pluginName = "ai-proxy"

	defaultMaxBodyBytes             uint32 = 100 * 1024 * 1024
	errorResponseBodyBufferLimit    uint32 = 64 * 1024
	maxLoggedErrorResponseBodyBytes        = 16 * 1024

	ctxOriginalPath                = "original_path"
	ctxOriginalHost                = "original_host"
	ctxOriginalAuth                = "original_auth"
	ctxUpstreamErrorResponseStatus = "upstream_error_response_status"
)

const headerContentLength = "Content-Length"

type pair[K, V any] struct {
	key   K
	value V
}

var (
	headersCtxKeyMapping = map[string]string{
		util.HeaderAuthority: ctxOriginalHost,
		util.HeaderPath:      ctxOriginalPath,
	}
	headerToOriginalHeaderMapping = map[string]string{
		util.HeaderAuthority: util.HeaderOriginalHost,
		util.HeaderPath:      util.HeaderOriginalPath,
	}
	pathSuffixToApiName = []pair[string, provider.ApiName]{
		// OpenAI style
		{provider.PathOpenAIChatCompletions, provider.ApiNameChatCompletion},
		{provider.PathOpenAICompletions, provider.ApiNameCompletion},
		{provider.PathOpenAIEmbeddings, provider.ApiNameEmbeddings},
		{provider.PathOpenAIAudioSpeech, provider.ApiNameAudioSpeech},
		{provider.PathOpenAIAudioTranscriptions, provider.ApiNameAudioTranscription},
		{provider.PathOpenAIAudioTranslations, provider.ApiNameAudioTranslation},
		{provider.PathOpenAIRealtime, provider.ApiNameRealtime},
		{provider.PathOpenAIImageGeneration, provider.ApiNameImageGeneration},
		{provider.PathOpenAIImageVariation, provider.ApiNameImageVariation},
		{provider.PathOpenAIImageEdit, provider.ApiNameImageEdit},
		{provider.PathOpenAIBatches, provider.ApiNameBatches},
		{provider.PathOpenAIFiles, provider.ApiNameFiles},
		{provider.PathOpenAIModels, provider.ApiNameModels},
		{provider.PathOpenAIFineTuningJobs, provider.ApiNameFineTuningJobs},
		{provider.PathOpenAIResponses, provider.ApiNameResponses},
		{provider.PathOpenAIVideos, provider.ApiNameVideos},
		// Anthropic style
		{provider.PathAnthropicMessagesCountTokens, provider.ApiNameAnthropicCountTokens},
		{provider.PathAnthropicMessages, provider.ApiNameAnthropicMessages},
		{provider.PathAnthropicComplete, provider.ApiNameAnthropicComplete},
		// Cohere style
		{provider.PathCohereV1Rerank, provider.ApiNameCohereV1Rerank},
		// Qwen style
		{provider.PathQwenV1Reranks, provider.ApiNameQwenV1Rerank},
		{provider.PathQwenV1Conversations, provider.ApiNameQwenV1Conversations},
	}
	pathPatternToApiName = []pair[*regexp.Regexp, provider.ApiName]{
		// OpenAI style
		{util.RegRetrieveBatchPath, provider.ApiNameRetrieveBatch},
		{util.RegCancelBatchPath, provider.ApiNameCancelBatch},
		{util.RegRetrieveFilePath, provider.ApiNameRetrieveFile},
		{util.RegRetrieveFileContentPath, provider.ApiNameRetrieveFileContent},
		{util.RegRetrieveVideoPath, provider.ApiNameRetrieveVideo},
		{util.RegRetrieveVideoContentPath, provider.ApiNameRetrieveVideoContent},
		{util.RegVideoRemixPath, provider.ApiNameVideoRemix},
		{util.RegRetrieveFineTuningJobPath, provider.ApiNameRetrieveFineTuningJob},
		{util.RegRetrieveFineTuningJobEventsPath, provider.ApiNameFineTuningJobEvents},
		{util.RegRetrieveFineTuningJobCheckpointsPath, provider.ApiNameFineTuningJobCheckpoints},
		{util.RegCancelFineTuningJobPath, provider.ApiNameCancelFineTuningJob},
		{util.RegResumeFineTuningJobPath, provider.ApiNameResumeFineTuningJob},
		{util.RegPauseFineTuningJobPath, provider.ApiNamePauseFineTuningJob},
		{util.RegFineTuningCheckpointPermissionPath, provider.ApiNameFineTuningCheckpointPermissions},
		{util.RegDeleteFineTuningCheckpointPermissionPath, provider.ApiNameDeleteFineTuningCheckpointPermission},
		// Gemini style
		{util.RegGeminiGenerateContent, provider.ApiNameGeminiGenerateContent},
		{util.RegGeminiStreamGenerateContent, provider.ApiNameGeminiStreamGenerateContent},
	}
)

func main() {}

func init() {
	wrapper.SetCtx(
		pluginName,
		wrapper.ParseOverrideConfig(parseGlobalConfig, parseOverrideRuleConfig),
		wrapper.ProcessRequestHeaders(onHttpRequestHeader),
		wrapper.ProcessStreamingRequestBodyWithAction(onHttpStreamingRequestBody),
		wrapper.ProcessResponseHeaders(onHttpResponseHeaders),
		wrapper.ProcessStreamingResponseBody(onStreamingResponseBody),
		wrapper.ProcessResponseBody(onHttpResponseBody),
		wrapper.ProcessStreamDone(onStreamDone),
		wrapper.WithRebuildMaxMemBytes[config.PluginConfig](200*1024*1024),
	)
}

func parseGlobalConfig(json gjson.Result, pluginConfig *config.PluginConfig) error {
	log.Debugf("loading global config: %s", json.String())

	pluginConfig.FromJson(json)
	if err := pluginConfig.Validate(); err != nil {
		log.Errorf("global rule config is invalid: %v", err)
		return err
	}
	if err := pluginConfig.Complete(); err != nil {
		log.Errorf("failed to apply global rule config: %v", err)
		return err
	}
	applyStreamTuning(json)

	return nil
}

func parseOverrideRuleConfig(json gjson.Result, global config.PluginConfig, pluginConfig *config.PluginConfig) error {
	log.Debugf("loading override rule config: %s", json.String())

	*pluginConfig = global

	pluginConfig.FromJson(json)
	if err := pluginConfig.Validate(); err != nil {
		log.Errorf("overridden rule config is invalid: %v", err)
		return err
	}
	if err := pluginConfig.Complete(); err != nil {
		log.Errorf("failed to apply overridden rule config: %v", err)
		return err
	}

	return nil
}

func initContext(ctx wrapper.HttpContext) {
	for header, ctxKey := range headersCtxKeyMapping {
		value, _ := proxywasm.GetHttpRequestHeader(header)
		ctx.SetContext(ctxKey, value)
	}
	for _, originHeader := range headerToOriginalHeaderMapping {
		_ = proxywasm.RemoveHttpRequestHeader(originHeader)
	}

	// Distinguish "first hop into this gateway" from "internal_redirect re-entry".
	//
	// Signal: x-higress-fallback-from. It is set by Envoy custom_response's
	// RedirectPolicy on every internal_redirect within this gateway, and it
	// survives mutateRequestHeaders on the redirected stream (it is NOT in
	// Envoy's hardcoded strip list).
	//
	// Absence  => first hop. Distrust any incoming X-HI-ORIGINAL-AUTH — it may
	//             have been set by a client or by an upstream cascaded gateway
	//             running its own ai-proxy. Re-anchor the saved value from the
	//             request's current Authorization, which is what this gateway
	//             should treat as the "original" credential for later
	//             internal_redirect hops.
	// Presence => internal_redirect re-entry within this gateway. Leave
	//             X-HI-ORIGINAL-AUTH alone — it preserves the value this gateway's
	//             ai-proxy wrote on the previous pass, which key-auth needs for
	//             re-authentication after Authorization has been replaced with
	//             the upstream apiToken.
	//
	// SAFETY DEPENDENCY: this signal is reliable only when external callers
	// cannot supply x-higress-fallback-from. For cascaded deployments where an
	// upstream gateway may itself be in an internal_redirect chain when forwarding
	// to this gateway, list x-higress-fallback-from (and x-hi-original-auth) in
	// the HCM internal_only_headers as defense-in-depth.
	fallbackFrom, _ := proxywasm.GetHttpRequestHeader(util.HeaderHigressFallbackFrom)
	if fallbackFrom == "" {
		_ = proxywasm.RemoveHttpRequestHeader(util.HeaderOriginalAuth)
		value, _ := proxywasm.GetHttpRequestHeader(util.HeaderAuthorization)
		if value != "" {
			ctx.SetContext(ctxOriginalAuth, value)
		}
	}
}

func saveContextsToHeaders(ctx wrapper.HttpContext) {
	for header, ctxKey := range headersCtxKeyMapping {
		originalValue := ctx.GetStringContext(ctxKey, "")
		if originalValue == "" {
			continue
		}
		currentValue, _ := proxywasm.GetHttpRequestHeader(header)
		if currentValue == "" || originalValue == currentValue {
			continue
		}
		originalHeader := headerToOriginalHeaderMapping[header]
		if originalHeader != "" {
			_ = proxywasm.ReplaceHttpRequestHeader(originalHeader, originalValue)
		}
	}
	originalValue := ctx.GetStringContext(ctxOriginalAuth, "")
	if originalValue != "" {
		_ = proxywasm.ReplaceHttpRequestHeader(util.HeaderOriginalAuth, originalValue)
	}
}

func onHttpRequestHeader(ctx wrapper.HttpContext, pluginConfig config.PluginConfig) types.Action {
	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpRequestHeader] no active provider, skip processing")
		ctx.DontReadRequestBody()
		return types.ActionContinue
	}

	log.Debugf("[onHttpRequestHeader] provider=%s", activeProvider.GetProviderType())

	// Disable the route re-calculation since the plugin may modify some headers related to the chosen route.
	ctx.DisableReroute()

	initContext(ctx)

	rawPath := ctx.Path()

	defer func() {
		saveContextsToHeaders(ctx)
	}()

	path, _ := url.Parse(rawPath)
	apiName := getApiName(path.Path)
	providerConfig := pluginConfig.GetProviderConfig()
	if providerConfig.IsOriginal() {
		if handler, ok := activeProvider.(provider.ApiNameHandler); ok {
			apiName = handler.GetApiName(path.Path)
		}
	} else {
		// Only perform protocol conversion for non-original protocols.
		// Auto-detect protocol based on request path and handle conversion if needed
		// If request is Claude format (/v1/messages) but provider doesn't support it natively,
		// convert to OpenAI format (/v1/chat/completions)
		if apiName == provider.ApiNameAnthropicMessages && !providerConfig.IsSupportedAPI(provider.ApiNameAnthropicMessages) {
			// Provider doesn't support Claude protocol natively, convert to OpenAI format
			newPath := strings.Replace(path.Path, provider.PathAnthropicMessages, provider.PathOpenAIChatCompletions, 1)
			_ = proxywasm.ReplaceHttpRequestHeader(":path", newPath)
			// Update apiName to match the new path
			apiName = provider.ApiNameChatCompletion
			// Mark that we need to convert response back to Claude format
			ctx.SetContext("needClaudeResponseConversion", true)
			log.Debugf("[Auto Protocol] Claude request detected, provider doesn't support natively, converted path from %s to %s, apiName: %s", path.Path, newPath, apiName)
		} else if apiName == provider.ApiNameAnthropicMessages {
			// Provider supports Claude protocol natively, no conversion needed
			log.Debugf("[Auto Protocol] Claude request detected, provider supports natively, keeping original path: %s, apiName: %s", path.Path, apiName)
		}
	}

	if contentType, _ := proxywasm.GetHttpRequestHeader(util.HeaderContentType); contentType != "" && !isSupportedRequestContentType(apiName, contentType) {
		ctx.DontReadRequestBody()
		log.Debugf("[onHttpRequestHeader] unsupported content type for api %s: %s, will not process the request body", apiName, contentType)
	}

	if apiName == "" {
		ctx.DontReadRequestBody()
		ctx.DontReadResponseBody()
		log.Warnf("[onHttpRequestHeader] unsupported path: %s, will not process http path and body", path.Path)
	}

	ctx.SetContext(provider.CtxKeyApiName, apiName)

	// Always remove the Accept-Encoding header to prevent the LLM from sending compressed responses,
	// allowing plugins to inspect or modify the response correctly
	_ = proxywasm.RemoveHttpRequestHeader("Accept-Encoding")

	_, hasRequestBodyHandler := activeProvider.(provider.RequestBodyHandler)
	hasRequestBody := ctx.HasRequestBody()
	if hasRequestBody && hasRequestBodyHandler && requestContentLengthExceedsLimit(defaultMaxBodyBytes) {
		_ = proxywasm.SendHttpResponseWithDetail(
			http.StatusRequestEntityTooLarge,
			"request_payload_too_large",
			util.CreateHeaders(util.HeaderContentType, util.MimeTypeTextPlain),
			[]byte("request payload too large"),
			-1,
		)
		return types.ActionPause
	}

	if handler, ok := activeProvider.(provider.RequestHeadersHandler); ok {
		// Set the apiToken for the current request.
		providerConfig.SetApiTokenInUse(ctx)
		// Set available apiTokens of current request in the context, will be used in the retryOnFailure
		providerConfig.SetAvailableApiTokens(ctx)

		// save the original request host and path in case they are needed for apiToken health check and retry
		ctx.SetContext(provider.CtxRequestHost, ctx.Host())
		ctx.SetContext(provider.CtxRequestPath, ctx.Path())

		err := handler.OnRequestHeaders(ctx, apiName)
		if err != nil {
			_ = util.ErrorHandler("ai-proxy.proc_req_headers_failed", fmt.Errorf("failed to process request headers: %v", err))
			return types.ActionContinue
		}

		if hasRequestBody && hasRequestBodyHandler {
			// Keep the declared size before dropping the header: admission needs it to tell whether diverting
			// a request to the buffered path would cost more memory than admitting it.
			if v, err := proxywasm.GetHttpRequestHeader(headerContentLength); err == nil {
				if n, err := strconv.ParseInt(strings.TrimSpace(v), 10, 64); err == nil && n > 0 {
					ctx.SetContext(ctxKeyDeclaredBodyBytes, n)
				}
			}
			_ = proxywasm.RemoveHttpRequestHeader(headerContentLength)
			ctx.SetRequestBodyBufferLimit(defaultMaxBodyBytes)
			// Delay the header processing to allow changing in OnRequestBody
			return types.HeaderStopIteration
		}
		ctx.DontReadRequestBody()
		return types.ActionContinue
	}

	return types.ActionContinue
}

func requestContentLengthExceedsLimit(limit uint32) bool {
	contentLength, _ := proxywasm.GetHttpRequestHeader(headerContentLength)
	if contentLengthExceedsLimit(contentLength, limit) {
		return true
	}

	headers, err := proxywasm.GetHttpRequestHeaders()
	if err != nil {
		return false
	}
	for _, header := range headers {
		if strings.EqualFold(header[0], headerContentLength) {
			return contentLengthExceedsLimit(header[1], limit)
		}
	}
	return false
}

func contentLengthExceedsLimit(contentLength string, limit uint32) bool {
	contentLength = strings.TrimSpace(contentLength)
	if contentLength == "" {
		return false
	}

	length, err := strconv.ParseUint(contentLength, 10, 64)
	if err != nil {
		if numErr, ok := err.(*strconv.NumError); ok && numErr.Err == strconv.ErrRange {
			return true
		}
		return false
	}
	return length > uint64(limit)
}

// onHttpStreamingRequestBody handles the request body chunk by chunk (layer 3: Guard).
//
// The request headers are held in the header phase (HeaderStopIteration) until this function first returns ActionContinue.
// So before the commit point it always returns ActionPause: the raw bytes stay in the Envoy buffer (on the order of CommitBytes)
// and the transformer's output is kept as well. A bail inside that window switches to the buffered path, a clean fallback;
// a bail after the commit point cannot take back the bytes already sent upstream, so the request can only fail.
//
// Facts that affect the request headers (stream / model) are applied before release; those that appear later can only become context keys.
func onHttpStreamingRequestBody(ctx wrapper.HttpContext, pluginConfig config.PluginConfig, chunk []byte, isLastChunk bool) ([]byte, types.Action) {
	st, _ := ctx.GetContext(ctxKeyXformState).(*xformState)
	if st == nil {
		st = newXformState(ctx, pluginConfig)
		ctx.SetContext(ctxKeyXformState, st)
	}
	return st.feed(chunk, isLastChunk)
}

const ctxKeyXformState = "aip_xform_state"

// Tuning knobs for the streaming path, read from the plugin config.
//
// Both are operational levers with measured effect and no behavioural consequence, so they are configuration
// rather than constants. The commit window bounds what one in-flight request holds before anything is
// released: 64KB down to 16KB cuts that to a quarter, at the cost of falling back more often, because a shape
// the transform cannot handle has to be found inside the window to be recoverable. The GC floor is the heap
// size below which the watchdog never forces a collection: 64MB down to 32MB halves the fixed floor each wasm
// VM sits at, at the cost of collecting more often.
//
// Zero means "leave the default": 64KB for the window (streamxform.CommitBytes), 64MB for the floor
// (wrapper.GCWatchdogFloor).
var streamCommitWindowBytes int

// streamTypeCheck turns off the root-field type checking that reproduces the buffered path's rejection surface.
//
// It exists for rollout, not for tuning. The check makes the gateway stricter: a request with a wrongly typed
// field used to be forwarded to the provider and now fails at the gateway, which is what the buffered path has
// always done but is a visible change for anyone who had come to rely on the looser behaviour. A deployment
// that needs to roll it back can, without going back to an older build.
var streamTypeCheck = true

// streamEarlyCommit commits as soon as a request's headers no longer depend on anything still to come,
// instead of holding a full commit window first.
//
// The window keeps a retreat open -- until it fills, a shape the transform cannot handle can still fall back
// to the buffered path. Measured on this gateway, legitimate traffic never takes that retreat (1.2 million
// requests in a soak, zero fallbacks): the fallback triggers are all malformed input, which fails on either
// path. What the window costs is real, though: every in-flight stream holds up to 64KB, which at 800
// concurrent 70KB requests is the whole difference between the streaming and buffered paths' memory. With
// this on, a request commits once model (and stream, where a header or path depends on it) has been seen --
// the first chunk for every SDK we know of -- and the window bounds only requests where that never happens.
//
// Off by default for rollout: it withdraws the guarantee that a body no larger than the window behaves
// exactly like the buffered path, and a deployment should turn that in with its eyes open.
var streamEarlyCommit = false

// applyStreamTuning reads the two knobs. Out-of-range values are logged and ignored rather than clamped: a
// wrong number in a config should be visible, not silently turned into a different one.
func applyStreamTuning(json gjson.Result) {
	if v := json.Get("streamCommitWindowBytes"); v.Exists() {
		n := int(v.Int())
		switch {
		case n == 0:
			streamCommitWindowBytes = 0
		case n < 4<<10 || n > 1<<20:
			log.Errorf("streamCommitWindowBytes %d out of range [4096, 1048576], keeping %d", n, effectiveCommitWindow())
		default:
			streamCommitWindowBytes = n
		}
	}
	if v := json.Get("streamInflightBudgetBytes"); v.Exists() {
		n := int(v.Int())
		switch {
		case n == 0:
			admBudgetBytes = 32 << 20
		case n < 1<<20 || n > 1<<30:
			log.Errorf("streamInflightBudgetBytes %d out of range [1048576, 1073741824], keeping %d", n, admBudgetBytes)
		default:
			admBudgetBytes = n
		}
	}
	if v := json.Get("streamEarlyCommit"); v.Exists() {
		streamEarlyCommit = v.Bool()
	}
	if v := json.Get("streamTypeCheck"); v.Exists() {
		streamTypeCheck = v.Bool()
		provider.ChatRequestTypeCheck = streamTypeCheck
	}
	if v := json.Get("streamGcFloorBytes"); v.Exists() {
		n := v.Int()
		switch {
		case n == 0:
			wrapper.GCWatchdogFloor = 64 << 20
		case n < 8<<20 || n > 512<<20:
			log.Errorf("streamGcFloorBytes %d out of range [8388608, 536870912], keeping %d", n, wrapper.GCWatchdogFloor)
		default:
			wrapper.GCWatchdogFloor = uint64(n)
		}
	}
	log.Infof("streaming tuning: commit window %d bytes, in-flight budget %d bytes (limit %.0f uploads), gc floor %d bytes, root field type check %v, early commit %v",
		effectiveCommitWindow(), admBudgetBytes, admLimit(), wrapper.GCWatchdogFloor, streamTypeCheck, streamEarlyCommit)
}

func effectiveCommitWindow() int {
	if streamCommitWindowBytes > 0 {
		return streamCommitWindowBytes
	}
	return streamxform.CommitBytes
}

// Admission control for the streaming path.
//
// Buffering the whole body has a side effect the streaming path loses: it caps how many requests are being
// uploaded to the upstream at the same time. Without that cap, thousands of concurrent uploads starve each
// other and throughput collapses (measured: the same collapse happens with no wasm filter at all, so it is a
// property of the data path, not of this plugin). Streaming therefore has to state the bound itself: past the
// current limit, new requests take the buffered path, which is exactly how the plugin behaved before.
//
// The bound is stated in bytes, not in requests, because bytes are what it is protecting. What one in-flight
// upload holds is one commit window, so a limit expressed as a request count silently means something different
// as soon as the window changes: 500 uploads is 32MB at the 64KB default and half a gigabyte at a 1MB window.
// The number of admitted uploads is therefore derived, and the two knobs cannot contradict each other:
//
//	limit = admBudgetBytes / commit window
//
// At the defaults that is 32MB / 64KB = 512, which is where the previously hand-picked 500 came from -- it is
// the same bound, now with a reason. Raising the window to 256KB lowers the limit to 128 on its own.
//
// An adaptive version is kept behind admAdaptive: every completed streaming request reports how long it took,
// the shortest time ever seen (with slow decay, so the baseline follows the upstream) is the reference, and the
// limit grows additively while requests finish quickly and is cut multiplicatively once they queue. It is off
// by default: on the lab gateway it walked the limit up to admMax, and 1MB bodies at 400 concurrency then
// showed a 1.6x larger Envoy heap (315-370MB of tcmalloc against 199-204MB) and a p99 of 37-42s against 15-18s,
// with no throughput to show for it. Turn it on only with that heap and tail latency under watch.
const (
	admLatencyOK  = 2  // finished within baseline x2: there is headroom, raise the limit by one
	admLatencyBad = 4  // took longer than baseline x4: requests are queueing, cut the limit to 0.9x
	admDecayEvery = 64 // every this many completions, relax the baseline by 1/8 so one freak minimum cannot pin it
)

var (
	streamInflight int
	// admBudgetBytes: how many bytes of in-flight streaming uploads one wasm VM may hold. This is the
	// incremental part only -- the Go heap floor the watchdog keeps and whatever else the VM allocates sit
	// on top of it -- and it is per VM, which means per Envoy worker: a gateway of three replicas with two
	// workers each holds six times this, so the cluster-wide figure is the one to size against a pod limit.
	admBudgetBytes = 32 << 20
	admOverride    = 0.0 // >0 pins the limit to a request count and ignores the budget; adaptive writes here
	admMin         = 50.0
	admMax         = 4000.0
	admAdaptive    = false // see above: adaptive costs Envoy heap and tail latency without buying throughput
	admBaseline    int64   // shortest completion time observed, in nanoseconds
	admDone        int
)

// admLimit is the number of in-flight streaming uploads this VM admits.
func admLimit() float64 {
	if admOverride > 0 {
		return admOverride
	}
	n := float64(admBudgetBytes) / float64(effectiveCommitWindow())
	if n < admMin {
		n = admMin
	}
	if n > admMax {
		n = admMax
	}
	return n
}

// admOnDone folds one request's completion time into the baseline, and into the limit when adaptive is on.
func admOnDone(dur int64) {
	if dur <= 0 {
		return
	}
	if admBaseline == 0 || dur < admBaseline {
		admBaseline = dur
	}
	admDone++
	if admDone%admDecayEvery == 0 {
		admBaseline += admBaseline / 8 // relax slowly so the baseline follows the real upstream
	}
	if !admAdaptive {
		return
	}
	if admOverride == 0 {
		admOverride = admLimit() // start adapting from the derived bound
	}
	switch {
	case dur <= admBaseline*admLatencyOK:
		if admOverride < admMax {
			admOverride++
		}
	case dur > admBaseline*admLatencyBad:
		admOverride *= 0.9
		if admOverride < admMin {
			admOverride = admMin
		}
	}
}

const (
	ctxKeyAdmitted          = "aip_xform_admitted"
	ctxKeyAdmitStart        = "aip_xform_admit_start"
	ctxKeyDeclaredBodyBytes = "aip_declared_body_bytes"
)

// admDivertRatio: past the limit a request is only diverted to the buffered path while its body is no larger
// than this many commit windows.
//
// Diverting is not free, and which way it costs depends on the body. The buffered path holds the whole body;
// the streaming path holds one window. Measured on the gateway: at 70KB bodies against a 64KB window --
// the two nearly equal -- diverting the excess at 5000 concurrency held 170MB less, because bytes move from
// wasm linear memory, which never shrinks, into Envoy's buffer, which does. At 1MB bodies against a 256KB
// window -- four times the window -- diverting 576 of 1857 requests instead cost 170MB more of Envoy heap
// (363MB against 190MB) and a third of the throughput. So the excess is diverted only while the two are
// comparable, and otherwise admitted: streaming a request the limit would have refused still holds less than
// buffering it.
const admDivertRatio = 2

// admDivert reports whether a request past the limit should go to the buffered path.
func admDivert(ctx wrapper.HttpContext) bool {
	n, _ := ctx.GetContext(ctxKeyDeclaredBodyBytes).(int64)
	if n <= 0 {
		return true // size not declared: keep the original behaviour
	}
	return n <= int64(admDivertRatio*effectiveCommitWindow())
}

// onStreamDone releases the admission slot. It runs even when the client aborts mid-upload, which the body
// hooks do not see; without it a few aborted requests would leak slots and pin the plugin to the buffered path.
func onStreamDone(ctx wrapper.HttpContext, pluginConfig config.PluginConfig) {
	if admitted, _ := ctx.GetContext(ctxKeyAdmitted).(bool); admitted {
		ctx.SetContext(ctxKeyAdmitted, false)
		if streamInflight > 0 {
			streamInflight--
		}
		if start, _ := ctx.GetContext(ctxKeyAdmitStart).(int64); start > 0 {
			admOnDone(time.Now().UnixNano() - start)
		}
	}
}

// Runtime metrics of the streaming path. The fallback rate must be watched after rollout: a fallback means full buffering, sized for the worst case until the rate is near zero.
// Metrics are observation only: when the host does not support them (the test emulator, or a deployment with metrics disabled) they switch off silently and never affect the request.
var (
	streamXformCounters   = map[string]proxywasm.MetricCounter{}
	streamXformMetricsOff bool
)

func streamXformCount(name string) {
	if streamXformMetricsOff {
		return
	}
	defer func() {
		if r := recover(); r != nil {
			streamXformMetricsOff = true
			log.Warnf("[stream-xform] metrics disabled: %v", r)
		}
	}()
	key := "ai_proxy.stream_xform." + name
	counter, ok := streamXformCounters[key]
	if !ok {
		counter = proxywasm.DefineCounterMetric(key)
		streamXformCounters[key] = counter
	}
	counter.Increment(1)
}

type xformState struct {
	st      *guard.State
	plan    *provider.StreamPlan
	apiName provider.ApiName
	ctx     wrapper.HttpContext
	cfg     config.PluginConfig
}

func newXformState(ctx wrapper.HttpContext, cfg config.PluginConfig) *xformState {
	x := &xformState{ctx: ctx, cfg: cfg}
	pc := cfg.GetProviderConfig()
	fallbackOnly := func() *xformState {
		x.st = guard.New(&guard.Plan{Fallback: x.fallback, Metric: streamXformCount, Log: log.Warnf})
		x.st.ForceFallback()
		return x
	}
	if pc == nil {
		return fallbackOnly()
	}
	x.apiName, _ = ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
	plan, why := pc.NewStreamPlan(ctx, x.apiName, cfg.GetProvider())
	if plan == nil {
		log.Debugf("[stream-xform] not streaming: %s", why)
		streamXformCount("skipped")
		return fallbackOnly()
	}
	if float64(streamInflight) >= admLimit() {
		if admDivert(ctx) {
			// Too many uploads in flight already, and buffering this one costs no more than streaming it.
			streamXformCount("admission_fallback")
			return fallbackOnly()
		}
		// Past the limit, but this body is large enough that buffering it would hold more than streaming it.
		streamXformCount("admission_admitted_oversize")
	}
	streamInflight++
	ctx.SetContext(ctxKeyAdmitted, true)
	ctx.SetContext(ctxKeyAdmitStart, time.Now().UnixNano())
	if streamCommitWindowBytes > 0 && plan.Tr != nil {
		plan.Tr.SetCommitBytes(streamCommitWindowBytes) // before the first Write, which happens in Feed
	}
	x.plan = plan
	x.st = guard.New(&guard.Plan{
		Tr:          plan.Tr,
		Mode:        guard.Transform,
		Passthrough: plan.Passthrough,
		OnCommit:    x.onCommit,
		OnFinish:    x.onFinish,
		EarlyCommit: x.earlyCommit,
		Fallback:    x.fallback,
		Uncoverable: func(why string) {
			_ = util.ErrorHandler("ai-proxy.stream_xform_uncoverable", fmt.Errorf("streaming transform bailed after commit: %s", why))
		},
		Metric: streamXformCount,
		Log:    log.Warnf,
	})
	return x
}

func (x *xformState) feed(chunk []byte, last bool) ([]byte, types.Action) {
	return x.st.Feed(chunk, last)
}

// onCommit: before the headers are released for the first time. Fields the request path depends on (model / stream) that did not
// appear before the commit point mean fallback, where "bounded lookahead, fall back past the window" lands; stream not seen by the end of the body is false, no fallback needed.
func (x *xformState) onCommit(pre streamxform.Prelude, last bool) bool {
	if x.plan.Passthrough {
		// the buffered path does not touch the body: before the first chunk write back the original header info from the context (what its defer does)
		if x.plan.AfterPrelude != nil {
			x.plan.AfterPrelude(x.ctx, pre) // header work the buffered path does in the body phase without reading the body (Vertex raw auth)
		}
		saveContextsToHeaders(x.ctx)
		return true
	}
	if (x.plan.RequireModelBeforeCommit && !pre.ModelSeen) || (x.plan.RequireStreamBeforeCommit && !pre.StreamSeen && !last) {
		log.Warnf("[stream-xform] fields required by the request path not seen before the commit point, falling back to the buffered path")
		return false
	}
	x.cfg.GetProviderConfig().StreamApplyPrelude(x.ctx, x.apiName, x.plan, pre, true)
	if x.plan.AfterPrelude != nil {
		x.plan.AfterPrelude(x.ctx, pre)
	}
	saveContextsToHeaders(x.ctx)
	return true
}

// earlyCommit reports whether the headers no longer depend on anything still to come: model has been seen
// (every plan applies it), and stream too where the plan says a header or path needs it. Passthrough plans
// have nothing to wait for. Only consulted when streamEarlyCommit is on.
func (x *xformState) earlyCommit(pre streamxform.Prelude) bool {
	if !streamEarlyCommit {
		return false
	}
	if x.plan.Passthrough {
		return true
	}
	if x.plan.ApplyModel && !pre.ModelSeen {
		return false
	}
	if x.plan.RequireStreamBeforeCommit && !pre.StreamSeen {
		return false
	}
	return true
}

func (x *xformState) onFinish(pre streamxform.Prelude) {
	if x.plan.Passthrough {
		return
	}
	pc := x.cfg.GetProviderConfig()
	pc.StreamApplyPrelude(x.ctx, x.apiName, x.plan, pre, false)
	pc.StreamFinalizeContext(x.ctx, x.apiName, x.plan, pre)
	if x.plan.OnFinish != nil {
		x.plan.OnFinish(x.ctx)
	}
}

// fallback is the buffered path.
func (x *xformState) fallback(body []byte) types.Action {
	return onHttpRequestBody(x.ctx, x.cfg, body)
}

func onHttpRequestBody(ctx wrapper.HttpContext, pluginConfig config.PluginConfig, body []byte) types.Action {
	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpRequestBody] no active provider, skip processing")
		return types.ActionContinue
	}
	log.Debugf("[onHttpRequestBody] provider=%s", activeProvider.GetProviderType())

	defer func() {
		saveContextsToHeaders(ctx)
	}()

	if handler, ok := activeProvider.(provider.RequestBodyHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		providerConfig := pluginConfig.GetProviderConfig()
		// If retryOnFailure is enabled, save the transformed body to the context in case of retry
		if providerConfig.IsRetryOnFailureEnabled() {
			ctx.SetContext(provider.CtxRequestBody, body)
		}
		newBody, settingErr := providerConfig.ReplaceByCustomSettings(body)
		if settingErr != nil {
			log.Errorf("failed to replace request body by custom settings: %v", settingErr)
		}
		// 仅 /v1/chat/completions 和 /v1/completions 接口支持 stream_options 参数
		// generic provider 不做能力映射，不添加 stream_options
		if providerConfig.IsOpenAIProtocol() && !providerConfig.IsGeneric() && (apiName == provider.ApiNameChatCompletion || apiName == provider.ApiNameCompletion) {
			newBody = normalizeOpenAiRequestBody(newBody, providerConfig.IsStreamUsageStatsDisabled())
		}
		log.Debugf("[onHttpRequestBody] newBody=%s", newBody)
		body = newBody
		action, err := handler.OnRequestBody(ctx, apiName, body)
		if err == nil {
			return action
		}
		log.Errorf("[onHttpRequestBody] failed to process request body, apiName=%s, err=%v", apiName, err)
		_ = util.ErrorHandler("ai-proxy.proc_req_body_failed", fmt.Errorf("failed to process request body: %v", err))
	}
	return types.ActionContinue
}

func onHttpResponseHeaders(ctx wrapper.HttpContext, pluginConfig config.PluginConfig) types.Action {
	if !wrapper.IsResponseFromUpstream() {
		// Response is not coming from the upstream. Let it pass through.
		ctx.DontReadResponseBody()
		return types.ActionContinue
	}

	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpResponseHeaders] no active provider, skip processing")
		ctx.DontReadResponseBody()
		return types.ActionContinue
	}

	log.Debugf("[onHttpResponseHeaders] provider=%s", activeProvider.GetProviderType())

	providerConfig := pluginConfig.GetProviderConfig()
	apiTokenInUse := providerConfig.GetApiTokenInUse(ctx)
	apiTokens := providerConfig.GetAvailableApiToken(ctx)

	status, err := proxywasm.GetHttpResponseHeader(":status")
	if err != nil || status != "200" {
		if err != nil {
			log.Errorf("unable to load :status header from response: %v", err)
		}
		action := providerConfig.OnRequestFailed(activeProvider, ctx, apiTokenInUse, apiTokens, status)
		if action == types.ActionContinue &&
			providerConfig.GetLogUpstreamErrorResponseBody() &&
			shouldLogUpstreamErrorResponse(status) {
			ctx.SetContext(ctxUpstreamErrorResponseStatus, status)
			ctx.BufferResponseBody()
			ctx.SetResponseBodyBufferLimit(errorResponseBodyBufferLimit)
			return action
		}
		ctx.DontReadResponseBody()
		return action
	}

	// Reset ctxApiTokenRequestFailureCount if the request is successful,
	// the apiToken is removed only when the number of consecutive request failures exceeds the threshold.
	providerConfig.ResetApiTokenRequestFailureCount(apiTokenInUse)

	headers := util.GetResponseHeaders()
	if handler, ok := activeProvider.(provider.TransformResponseHeadersHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		handler.TransformResponseHeaders(ctx, apiName, headers)
	} else {
		providerConfig.DefaultTransformResponseHeaders(ctx, headers)
	}
	util.ReplaceResponseHeaders(headers)

	_, needHandleBody := activeProvider.(provider.TransformResponseBodyHandler)
	var needHandleStreamingBody bool
	_, needHandleStreamingBody = activeProvider.(provider.StreamingResponseBodyHandler)
	if !needHandleStreamingBody {
		_, needHandleStreamingBody = activeProvider.(provider.StreamingEventHandler)
	}

	// Check if we need to read body for Claude response conversion
	needClaudeConversion, _ := ctx.GetContext("needClaudeResponseConversion").(bool)

	if !needHandleBody && !needHandleStreamingBody && !needClaudeConversion {
		ctx.DontReadResponseBody()
	} else {
		checkStream(ctx)
	}

	return types.ActionContinue
}

func onStreamingResponseBody(ctx wrapper.HttpContext, pluginConfig config.PluginConfig, chunk []byte, isLastChunk bool) []byte {
	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onStreamingResponseBody] no active provider, skip processing")
		return chunk
	}

	promoteThinking := pluginConfig.GetProviderConfig().GetPromoteThinkingOnEmpty()

	log.Debugf("[onStreamingResponseBody] provider=%s", activeProvider.GetProviderType())
	log.Debugf("[onStreamingResponseBody] isLastChunk=%v chunk: %s", isLastChunk, string(chunk))

	if handler, ok := activeProvider.(provider.StreamingResponseBodyHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		modifiedChunk, err := handler.OnStreamingResponseBody(ctx, apiName, chunk, isLastChunk)
		if err == nil && modifiedChunk != nil {
			if promoteThinking {
				modifiedChunk = promoteThinkingInStreamingChunk(ctx, modifiedChunk, isLastChunk)
			}
			// Convert to Claude format if needed
			claudeChunk, convertErr := convertStreamingResponseToClaude(ctx, modifiedChunk)
			if convertErr != nil {
				return modifiedChunk
			}
			return claudeChunk
		}
		return chunk
	}
	if handler, ok := activeProvider.(provider.StreamingEventHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		events := provider.ExtractStreamingEvents(ctx, chunk)
		log.Debugf("[onStreamingResponseBody] %d events received", len(events))
		if len(events) == 0 {
			// No events are extracted, return empty bytes slice
			return []byte("")
		}
		var responseBuilder strings.Builder
		for _, event := range events {
			log.Debugf("processing event: %v", event)

			if event.IsEndData() {
				responseBuilder.WriteString(event.ToHttpString())
				continue
			}

			outputEvents, err := handler.OnStreamingEvent(ctx, apiName, event)
			if err != nil {
				log.Errorf("[onStreamingResponseBody] failed to process streaming event: %v\n%s", err, chunk)
				return chunk
			}
			if len(outputEvents) == 0 {
				// no need convert, keep original events
				responseBuilder.WriteString(event.RawEvent)
			} else {
				for _, outputEvent := range outputEvents {
					responseBuilder.WriteString(outputEvent.ToHttpString())
				}
			}
		}

		result := []byte(responseBuilder.String())

		if promoteThinking {
			result = promoteThinkingInStreamingChunk(ctx, result, isLastChunk)
		}

		// Convert to Claude format if needed
		claudeChunk, convertErr := convertStreamingResponseToClaude(ctx, result)
		if convertErr != nil {
			return result
		}
		return claudeChunk
	}

	if !needsClaudeResponseConversion(ctx) && !promoteThinking {
		return chunk
	}

	// If provider doesn't implement any streaming handlers but we need Claude conversion
	// or thinking promotion
	// First extract complete events from the chunk
	events := provider.ExtractStreamingEvents(ctx, chunk)
	log.Debugf("[onStreamingResponseBody] %d events received (no handler)", len(events))
	if len(events) == 0 {
		// No events are extracted, return empty bytes slice
		return []byte("")
	}

	// Build response from extracted events (without handler processing)
	var responseBuilder strings.Builder
	for _, event := range events {
		responseBuilder.WriteString(event.ToHttpString())
	}

	result := []byte(responseBuilder.String())

	if promoteThinking {
		result = promoteThinkingInStreamingChunk(ctx, result, isLastChunk)
	}

	// Convert to Claude format if needed
	claudeChunk, convertErr := convertStreamingResponseToClaude(ctx, result)
	if convertErr != nil {
		return result
	}
	return claudeChunk
}

func onHttpResponseBody(ctx wrapper.HttpContext, pluginConfig config.PluginConfig, body []byte) types.Action {
	activeProvider := pluginConfig.GetProvider()

	if activeProvider == nil {
		log.Debugf("[onHttpResponseBody] no active provider, skip processing")
		return types.ActionContinue
	}

	log.Debugf("[onHttpResponseBody] provider=%s", activeProvider.GetProviderType())

	if status := ctx.GetStringContext(ctxUpstreamErrorResponseStatus, ""); status != "" {
		logUpstreamErrorResponse(ctx, activeProvider, status, body)
		return types.ActionContinue
	}

	var finalBody []byte

	if handler, ok := activeProvider.(provider.TransformResponseBodyHandler); ok {
		apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
		transformedBody, err := handler.TransformResponseBody(ctx, apiName, body)
		if err != nil {
			_ = util.ErrorHandler("ai-proxy.proc_resp_body_failed", fmt.Errorf("failed to process response body: %v", err))
			return types.ActionContinue
		}
		finalBody = transformedBody
	} else {
		finalBody = body
	}

	// Promote thinking/reasoning to content when content is empty
	if pluginConfig.GetProviderConfig().GetPromoteThinkingOnEmpty() {
		promoted, err := provider.PromoteThinkingOnEmptyResponse(finalBody)
		if err != nil {
			log.Warnf("[promoteThinkingOnEmpty] failed: %v", err)
		} else {
			finalBody = promoted
		}
	}

	// Convert to Claude format if needed (applies to both branches)
	convertedBody, err := convertResponseBodyToClaude(ctx, finalBody)
	if err != nil {
		_ = util.ErrorHandler("ai-proxy.convert_resp_to_claude_failed", err)
		return types.ActionContinue
	}

	if err = provider.ReplaceResponseBody(convertedBody); err != nil {
		_ = util.ErrorHandler("ai-proxy.replace_resp_body_failed", fmt.Errorf("failed to replace response body: %v", err))
	}
	return types.ActionContinue
}

func shouldLogUpstreamErrorResponse(status string) bool {
	code, err := strconv.Atoi(status)
	if err != nil {
		return false
	}
	return code >= 400
}

func logUpstreamErrorResponse(ctx wrapper.HttpContext, activeProvider provider.Provider, status string, body []byte) {
	apiName, _ := ctx.GetContext(provider.CtxKeyApiName).(provider.ApiName)
	requestID := responseHeaderValue("x-request-id")
	if requestID == "" {
		requestID = responseHeaderValue("X-Request-Id")
	}
	bodyText, truncated := errorResponseBodyForLog(body)
	log.Warnf("[upstream_error_response] provider=%s apiName=%s status=%s request_id=%s original_model=%s final_model=%s body_truncated=%v body=%s",
		activeProvider.GetProviderType(),
		apiName,
		status,
		requestID,
		ctx.GetStringContext("originalRequestModel", ""),
		ctx.GetStringContext("finalRequestModel", ""),
		truncated,
		bodyText,
	)
}

func responseHeaderValue(name string) string {
	value, err := proxywasm.GetHttpResponseHeader(name)
	if err != nil {
		return ""
	}
	return value
}

func errorResponseBodyForLog(body []byte) (string, bool) {
	truncated := len(body) > maxLoggedErrorResponseBodyBytes
	if truncated {
		body = body[:maxLoggedErrorResponseBodyBytes]
	}
	text := strings.ToValidUTF8(string(body), "?")
	text = strings.ReplaceAll(text, "\r", "\\r")
	text = strings.ReplaceAll(text, "\n", "\\n")
	return text, truncated
}

// Helper function to check if Claude response conversion is needed
func needsClaudeResponseConversion(ctx wrapper.HttpContext) bool {
	needClaudeConversion, _ := ctx.GetContext("needClaudeResponseConversion").(bool)
	return needClaudeConversion
}

// Helper function to convert OpenAI streaming response to Claude format
func convertStreamingResponseToClaude(ctx wrapper.HttpContext, data []byte) ([]byte, error) {
	if !needsClaudeResponseConversion(ctx) {
		return data, nil
	}

	// Get or create converter instance from context to maintain state
	const claudeConverterKey = "claudeConverter"
	var converter *provider.ClaudeToOpenAIConverter

	if converterData := ctx.GetContext(claudeConverterKey); converterData != nil {
		if c, ok := converterData.(*provider.ClaudeToOpenAIConverter); ok {
			converter = c
		}
	}

	if converter == nil {
		converter = &provider.ClaudeToOpenAIConverter{}
		ctx.SetContext(claudeConverterKey, converter)
	}

	claudeChunk, err := converter.ConvertOpenAIStreamResponseToClaude(ctx, data)
	if err != nil {
		log.Errorf("failed to convert streaming response to claude format: %v", err)
		return data, err
	}
	return claudeChunk, nil
}

// promoteThinkingInStreamingChunk processes SSE-formatted streaming data, buffering
// reasoning deltas and stripping them from chunks. On the last chunk, if no content
// was ever seen, it appends a flush chunk that emits buffered reasoning as content.
func promoteThinkingInStreamingChunk(ctx wrapper.HttpContext, data []byte, isLastChunk bool) []byte {
	// SSE data contains lines like "data: {...}\n\n"
	// We need to find and process each data line
	lines := strings.Split(string(data), "\n")
	modified := false
	for i, line := range lines {
		if !strings.HasPrefix(line, "data: ") {
			continue
		}
		payload := strings.TrimPrefix(line, "data: ")
		if payload == "[DONE]" || payload == "" {
			continue
		}
		stripped, err := provider.PromoteStreamingThinkingOnEmptyChunk(ctx, []byte(payload))
		if err != nil {
			continue
		}
		newLine := "data: " + string(stripped)
		if newLine != line {
			lines[i] = newLine
			modified = true
		}
	}

	result := data
	if modified {
		result = []byte(strings.Join(lines, "\n"))
	}

	// On last chunk, flush buffered reasoning as content if no content was seen
	if isLastChunk {
		flushChunk := provider.PromoteStreamingThinkingFlush(ctx)
		if flushChunk != nil {
			result = append(flushChunk, result...)
		}
	}

	return result
}

// Helper function to convert OpenAI response body to Claude format
func convertResponseBodyToClaude(ctx wrapper.HttpContext, body []byte) ([]byte, error) {
	if !needsClaudeResponseConversion(ctx) {
		return body, nil
	}

	converter := &provider.ClaudeToOpenAIConverter{}
	convertedBody, err := converter.ConvertOpenAIResponseToClaude(ctx, body)
	if err != nil {
		return body, fmt.Errorf("failed to convert response to claude format: %v", err)
	}
	return convertedBody, nil
}

func normalizeOpenAiRequestBody(body []byte, disableStreamUsageStats bool) []byte {
	if disableStreamUsageStats {
		return body
	}
	var err error
	// Default setting include_usage.
	if gjson.GetBytes(body, "stream").Bool() && (!gjson.GetBytes(body, "stream_options").Exists() || !gjson.GetBytes(body, "stream_options.include_usage").Exists()) {
		body, err = sjson.SetBytes(body, "stream_options.include_usage", true)
		if err != nil {
			log.Errorf("set include_usage failed, err:%s", err)
		}
	}
	return body
}

func checkStream(ctx wrapper.HttpContext) {
	contentType, err := proxywasm.GetHttpResponseHeader("Content-Type")
	if err != nil || !strings.HasPrefix(contentType, "text/event-stream") {
		if err != nil {
			log.Errorf("unable to load content-type header from response: %v", err)
		}
		ctx.BufferResponseBody()
		ctx.SetResponseBodyBufferLimit(defaultMaxBodyBytes)
	}
}

func getApiName(path string) provider.ApiName {
	// Check path suffix matches first
	for _, p := range pathSuffixToApiName {
		if strings.HasSuffix(path, p.key) {
			return p.value
		}
	}

	// Check path pattern matches
	for _, p := range pathPatternToApiName {
		if p.key.MatchString(path) {
			return p.value
		}
	}

	return ""
}

func isSupportedRequestContentType(apiName provider.ApiName, contentType string) bool {
	if strings.Contains(contentType, util.MimeTypeApplicationJson) {
		return true
	}
	contentType = strings.ToLower(contentType)
	if strings.HasPrefix(contentType, "multipart/form-data") {
		return apiName == provider.ApiNameImageEdit || apiName == provider.ApiNameImageVariation
	}
	return false
}
